language: go
# install: go get -v github.com/spf13/hugo
install:
  - go get -u -v github.com/kardianos/govendor
  - go get -u -v github.com/gohugoio/hugo
  - ( cd $GOPATH/src/github.com/gohugoio/hugo && govendor sync && go install )
script:
  - hugo
  - python --version
  - sudo pip install s3cmd
  - s3cmd --region=ap-southeast-2 sync --delete-removed -P --guess-mime-type --no-mime-magic -r public/ s3://rowe.lighting/
notifications:
    email:
        on_failure: always
