languageCode = "en-us"
title = "Michael Rowe - Lighting design"
baseurl = "//rowe.lighting/"

theme = "hugo-universal-theme"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-6154615-9"

# Define the number of posts per page
paginate = 10

[params]
    style = "default"
    description = "Michael Rowe - stage lighting design"
    author = "Michael Rowe"
    email = "michael@rowe.lighting"

    copyright = "Copyright (c) 1986-2018 Michael Rowe except where noted. All rights reserved."
    date_format = "2006-01-02"
    logo = "img/logo.png"
    # latitude = "-37.8137"
    # longitude = "144.9634"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "Portfolio"
    url  = "/portfolio/"
    weight = 2

[[params.menu]]
    name = "About"
    url  = "/about"
    weight = 3

[[params.menu]]
    name = "Current projects"
    url  = "/current-projects/"
    weight = 4

[[params.menu]]
    name = "Résumé"
    url  = "/resume"
    weight = 5

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false

[params.testimonials]
    enable = false

[params.recent_posts]
    enable = false
